from __future__ import annotations

from datetime import datetime

import pytest


@pytest.fixture
def source_snapshot() -> dict:
    return {
        "tenant": {
            "tenantId": "tenant-001",
            "participantId": 1,
            "ownership": "1001-tenant",
            "name": "Synthetic Tenant",
            "description": None,
            "contact": None,
            "mobilePhone": None,
            "officePhone": None,
            "code": "TENANT-001",
            "unifiedSocialCreditCode": None,
            "statusId": 2,
            "typeId": 1,
            "industryCode": None,
            "newTenantId": None,
            "iamLesseeId": None,
            "createDate": "2026-07-30T08:00:00",
            "lastUpdateDate": "2026-07-30T08:30:00",
            "rootOrgId": 10,
        },
        "organizations": [
            {
                "id": 10,
                "tenantId": "tenant-001",
                "ownership": "1001-root",
                "parentOrgId": 0,
                "no": "ROOT",
                "code": "ROOT-CODE",
                "name": "Root",
                "typeId": 1,
                "provinceCode": None,
                "cityCode": None,
                "address": "Synthetic address",
                "phone": None,
                "leader": None,
                "dataPermission": "1001-root",
                "remark": None,
                "orgNo": None,
                "systemCode": None,
                "easCode": None,
                "addressCoordinate": None,
                "cisOrgInfo": None,
                "participantCode": None,
                "userId": None,
                "deleted": False,
                "createDate": "2026-07-30T08:00:00",
                "lastUpdateDate": "2026-07-30T08:30:00",
            },
            {
                "id": 11,
                "tenantId": "tenant-001",
                "ownership": "1001-child",
                "parentOrgId": 10,
                "no": "CHILD",
                "code": "CHILD-CODE",
                "name": "Child",
                "typeId": 5,
                "provinceCode": None,
                "cityCode": None,
                "address": None,
                "phone": None,
                "leader": None,
                "dataPermission": "1001-root",
                "remark": None,
                "orgNo": None,
                "systemCode": None,
                "easCode": None,
                "addressCoordinate": None,
                "cisOrgInfo": None,
                "participantCode": None,
                "userId": None,
                "deleted": False,
                "createDate": "2026-07-30T08:01:00",
                "lastUpdateDate": "2026-07-30T08:31:00",
            },
        ],
        "staff": [
            {
                "id": staff_id,
                "tenantId": "tenant-001",
                "ownership": "1001-staff",
                "systemCode": None,
                "orgnizationId": 11,
                "loginName": f"staff_{staff_id}",
                "name": f"Staff {staff_id}",
                "email": None,
                "genderId": None,
                "mobilePhone": None,
                "headImg": None,
                "idCard": None,
                "jobNumber": f"NO-{staff_id}",
                "jobTitle": None,
                "birthday": None,
                "commonPlace": None,
                "accountOrgNo": None,
                "agentNo": None,
                "affiliateSubAccountId": None,
                "affiliateAccountAppQueueId": None,
                "affiliateAccountAppQueueNo": None,
                "wxUserId": None,
                "nailUserId": None,
                "workPhone": None,
                "isUserType": 7,
                "statusId": 2,
                "loginOrNot": True,
                "loginRetryTimes": 0,
                "accountLockedTime": None,
                "createDate": "2026-07-30T08:02:00",
                "lastUpdateDate": "2026-07-30T08:32:00",
            }
            for staff_id in (100, 101, 102)
        ],
        "captured_at": datetime(2026, 7, 30, 0, 40, 0).isoformat() + "Z",
    }


@pytest.fixture
def metadata() -> dict:
    return {
        "migrationBatchId": "batch-001",
        "legacyTenantId": "tenant-001",
        "enabledModules": ["TENANT", "ORGANIZATION", "STAFF"],
        "sourceTimezone": "Asia/Shanghai",
        "snapshotAt": "2026-07-30T00:40:00Z",
    }
